### PR TITLE
Fixed action sequence to include multiple actions

### LINKED ISSUE #4044: Weird scenario using performOn() with multiple fillField()
#### What are you trying to achieve?
Modal fillField using performOn(), seems only the last fillField() chain is called, since I have multiple fillField() call.

#### What do you get instead?
Only the last fillField() chain is called, nothing else, check my bash output.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
...
    Upload Photo
  First Name *
  Last Name *
  Email *
  Contact Number *
                              * Account For
                                                              Lol
                                                              Group HR
                                                              Chain HR
                                                              Enterprise HR
                                                              Hiring Officer
                                                              Event Supervisor

  CREATE
  CANCEL
  [Action] see "Create A New Account"
  [Action] fill field "#first_name","Pedro"
  [Action] select option "#role_slug","Lol"
  [Action] click "#pushcreate_new_account"
```
> Provide test source code if related

```php
I->performOn('#create-new-account', \Codeception\Util\ActionSequence::build()
    ->see('Create A New Account')
    ->fillField('#phone', '1234567890')
    ->fillField('#last_name', 'Dela Cruz')
    ->fillField('#email', sprintf('%s@%s.com', str_random('10'), str_random('5')))
    ->fillField('#first_name', 'Pedro')
    ->selectOption('#role_slug', 'Lol')
    ->click('#pushcreate_new_account')
    // ->waitForElement('#account-succesfully-created', 60)
    // ->see('Account Successfully Created', '#account-succesfully-created')
);
```

### Details

* Codeception version: 2.2.9
* PHP Version: PHP 7.0.8-2+deb.sury.org~xenial+1 (cli) ( NTS )
* Operating System: Ubuntu Vagrant (laravel homestead)
* Installation type: Composer
* Suite configuration: 
```
class_name: LolTester
modules:
    enabled:
      - WebDriver
      - \Helper\Lol
      - Laravel5:
          part: ORM
          cleanup: true
    config:
      WebDriver:
        url: '{something here...}'
        browser: phantomjs
        port: 9988
        capabilities:
            # phantomjs.page.settings.userAgent: "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36"
            phantomjs.page.settings.userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
```

### PR DESCRIPTION
**Pull request by DavertMik**
Fixes #4044

### CODE REVIEW

File: src/Codeception/Util/ActionSequence.php [hunk 1]
```diff
@@ -54,7 +56,9 @@ public static function build()
 
     public function __call($action, $arguments)
     {
-        $this->actions[$action] = $arguments;
+        $key = "{$this->counter}.$action";
```
Comment (Naktibalda) [inline src/Codeception/Util/ActionSequence.php]: Storing multiple pieces of information in a string is ugly, I think that it would be much more elegant to create `Action` object here.

Comment (DavertMik) [inline src/Codeception/Util/ActionSequence.php]: yes, I agree not a perfect solution. Ok, I think I can rework it.

For output this action sequence should be transformed to a list of actions. So I was thinking to make it as visible array. Right now I think the `ActionSequence` can provide `__toString` and won't be translated to array.

**Comment by DavertMik** [comment]
Improved, a code is a bit cleared; action sequence now executes actions on the context of given object.
I.e. it can clearly be used inside other modules. Current output look like this:

```
 I am on page "/form/example1"
  [GET] http://localhost:8000/form/example1
 I perform on ".rememberMe","see: 'Remember me', see: 'next time', dontSee: 'Login'"
  [InnerText] Remember me next time
  - see "Remember me"
  - see "next time"
  - don't see "Login"
 PASSED 
```
