### PR TITLE
Fixed issue #3653

### LINKED ISSUE #3653: Generate JUnit XML Log will failed when Selenium server can’t be connected
Hello,

I think that with the different change about improving WebDriver in 2.2.6 we break something when we are exporting xml file.

**Run test without exporting => OK it will print an error**

```
./vendor/bin/codecept run tests/acceptance/minimumRequirementsCest.php --env ie8                                                               
Codeception PHP Testing Framework v2.2.6
Powered by PHPUnit 5.6.2 by Sebastian Bergmann and contributors.

Acceptance (ie8) Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------
E minimumRequirementsCest: Test helium on internet explorer8 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 594 ms, Memory: 14.25MB

There was 1 error:

---------
1) minimumRequirementsCest: Test helium on internet explorer8
 Test  tests/acceptance/minimumRequirementsCest.php:testHeliumOnInternetExplorer8
JSON decoding of remote response failed.
Error code: 4
The response: 'Uh oh, you've run out of minutes!
Please visit https://saucelabs.com/pricing to purchase a subscription.'


ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Run test with xml export => It will fail in JUnit.php**

```
./vendor/bin/codecept run tests/acceptance/minimumRequirementsCest.php --env ie8 --xml result_acceptance_minrequirement.xml          
Codeception PHP Testing Framework v2.2.6
Powered by PHPUnit 5.6.2 by Sebastian Bergmann and contributors.

Acceptance (ie8) Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------
E minimumRequirementsCest: Test helium on internet explorer8 
PHP Fatal error:  Call to a member function setAttribute() on null in /home/vdauce/Code/iwqa/vendor/phpunit/phpunit/src/Util/Log/JUnit.php on line 375



FATAL ERROR. TESTS NOT FINISHED.
Call to a member function setAttribute() on null 
in /vendor/phpunit/phpunit/src/Util/Log/JUnit.php:375

```

The issue is about $this->currentTestCase that is null at the end of the test.

It was working well in 2.2.5.

@DavertMik I'm don't know JUnit.php so I will not fix it.

### PR DESCRIPTION
**Pull request by Naktibalda**
Fixes #3653

### CODE REVIEW

File: tests/cli/ExceptionInBeforeDoesNotMakeFatalErrorCept.php [hunk 1]
```diff
@@ -0,0 +1,6 @@
+<?php
+$I = new CliGuy($scenario);
+$I->wantTo('see that exception in before does not cause fatal error in after');
```
Comment (orlangur) [inline tests/cli/ExceptionInBeforeDoesNotMakeFatalErrorCept.php]: Any reason to not catch exception within listener?

Comment (Naktibalda) [inline tests/cli/ExceptionInBeforeDoesNotMakeFatalErrorCept.php]: Thanks for suggestion. Actually I haven't even looked at the listener.

**Comment by DavertMik** [comment]
Thanks
