### PR TITLE
ErrorHandler: add test for early exits

### LINKED ISSUE #5595: What is the purpose of Subscriber\ErrorHandler? Can we document it?
Hi, whenever using a simple `var_dump($var);exit;` in a test to do a trivial debugging, the output of a run is bloated by `ErrorHandler::shutdownHandler` output, that is registered as a shutdown function in the `SUITE_BEFORE` event.

```
$ vendor/bin/codecept run common/tests/unit/MyTest.php 
Codeception PHP Testing Framework v2.4.5
Powered by PHPUnit 7.5.6 by Sebastian Bergmann and contributors.

Common\tests\_support.unit Tests (1) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- MyTest: What
int(1)

PHP Fatal error:  Uncaught RuntimeException: Command Did Not Finish Properly in ./vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php:101
Stack trace:
#0 [internal function]: Codeception\Subscriber\ErrorHandler->shutdownHandler()
#1 {main}
  thrown in ./vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php on line 101

Fatal error: Uncaught RuntimeException: Command Did Not Finish Properly in ./vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php:101
Stack trace:
#0 [internal function]: Codeception\Subscriber\ErrorHandler->shutdownHandler()
#1 {main}
  thrown in ./vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php on line 101
```

What is the exact purpose of this?
Is all my code converts errors to exceptions, could I get rid of this handler?
Would you accept a PR to avoid subscribing this listener with a proper config in the `codeception.yml` file?

### PR DESCRIPTION
**Pull request by Slamdunk**
Closes #5595

Add test for #4604 /cc @Fenikkusu

### CODE REVIEW

File: src/Codeception/Subscriber/ErrorHandler.php [hunk 1]
```diff
@@ -98,8 +98,10 @@ public function shutdownHandler()
         if (!$this->suiteFinished && (
             $error === null || !in_array($error['type'], [E_ERROR, E_COMPILE_ERROR, E_CORE_ERROR])
         )) {
-            throw new \RuntimeException('Command Did Not Finish Properly');
-        } elseif (!is_array($error)) {
+            echo "\n\n\nCOMMAND DID NOT FINISH PROPERLY.\n";
+            return;
```
Comment (Naktibalda) [inline src/Codeception/Subscriber/ErrorHandler.php]: This would still look like successful run in CI system.
It would be better to use `die(1);` in order to set non-zero exist code.

Comment (Slamdunk) [reply src/Codeception/Subscriber/ErrorHandler.php]: I was deceived by `executeFailCommand`: I thought it would check that the command fails, instead it only accept possible failing commands:

https://github.com/Codeception/Codeception/blob/feb566a9dc26993611602011ae3834d8e3c1dd7f/src/Codeception/Module/Cli.php#L52-L54

PR updated.

This should be valid also for the `FATAL ERROR. TESTS NOT FINISHED.`, shouldn't it?

File: src/Codeception/Subscriber/ErrorHandler.php [hunk 2]
```diff
@@ -98,8 +98,10 @@ public function shutdownHandler()
         if (!$this->suiteFinished && (
             $error === null || !in_array($error['type'], [E_ERROR, E_COMPILE_ERROR, E_CORE_ERROR])
         )) {
-            throw new \RuntimeException('Command Did Not Finish Properly');
-        } elseif (!is_array($error)) {
+            echo "\n\n\nCOMMAND DID NOT FINISH PROPERLY.\n";
+            exit(255);
```
Comment (Slamdunk) [inline src/Codeception/Subscriber/ErrorHandler.php]: 255 is the code used by uncaught exception, so I retained the same number.

File: tests/cli/ErrorHandlerCest.php [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+class ErrorHandlerCest
+{
+    /**
+     * @param CliGuy $I
+     */
+    public function earlyExitWarnsTheUser(\CliGuy $I)
+    {
+        $I->executeFailCommand('run -c tests/data/first_test_exits');
+
+        $I->seeInShellOutput('COMMAND DID NOT FINISH PROPERLY');
```
Comment (Naktibalda) [inline tests/cli/ErrorHandlerCest.php]: I think that it would be useful to test exit code using [seeResultCodeIs](https://codeception.com/docs/modules/Cli#seeResultCodeIs)

Comment (Slamdunk) [reply tests/cli/ErrorHandlerCest.php]: Didn't know this, nice, implemented, thanks for the feedback
