### PR TITLE
Group Files not working with @example

### LINKED ISSUE #3278: Group Files not working with @example
Hello,

Fresh install of Codeception 2.2.1

In Acceptance Cest file (tests/acceptance/welcomeCest.php) :
```php
    /**
    * @example (url="https://www.google.fr")
    * @example (url="https://www.bing.com")
    * @example (url="https://duckduckgo.com")
    */
    public function tryToTest(AcceptanceTester $I, $scenario, \Codeception\Example $example)
    {
        $I->amOnUrl($example['url']);
    }
```

In acceptance suite yml:
```
groups:
    group1: tests/_data/group1
```

In tests/_data/group1:
`tests/acceptance/welcomeCest.php`

This command will execute no test:
`./vendor/bin/codecept run -g group1`

Maybe related to #2990

### PR DESCRIPTION
**Pull request by eXorus**
Fix #3278 

acceptance/welcomeCest.php :
```php
class welcomeCest
{
    public function testCase1(AcceptanceTester $I)
    {
        $I->amOnUrl('https://www.google.fr');
    }
    /**
    * @group grouptc2
    */
    public function testCase2(AcceptanceTester $I)
    {
        $I->amOnUrl('https://www.google.fr');
    }

    /**
    * @group grouptc3
    * @example (url="https://www.google.fr")
    * @example (url="https://www.bing.com")
    * @example (url="https://duckduckgo.com")
    */
    public function testCase3(AcceptanceTester $I, $scenario, \Codeception\Example $example)
    {
        $I->amOnUrl($example['url']);
    }
    /**
    * @example (url="https://www.google.fr")
    * @example (url="https://www.bing.com")
    * @example (url="https://duckduckgo.com")
    */
    public function testCase4(AcceptanceTester $I, $scenario, \Codeception\Example $example)
    {
        $I->amOnUrl($example['url']);
    }
}
```

acceptance.suite.yml:
```yml
groups:
    grouptc4: tests/_data/grouptc4
```
_data/grouptc4:
```
tests/acceptance/welcomeCest.php
```

**Result before the fix:**
run => tc1, tc2, tc3, tc4
run -g grouptc2 => tc2
run -g grouptc3 => tc3
run -g grouptc4 =>  tc1, tc2

**Result after the fix:**
run => tc1, tc2, tc3, tc4
run -g grouptc2 => tc2
run -g grouptc3 => tc3
run -g grouptc4 =>  tc1, tc2, tc3, tc4

### CODE REVIEW

File: src/Codeception/Lib/GroupManager.php [hunk 1]
```diff
@@ -104,6 +104,12 @@ public function groupsForTest(\PHPUnit_Framework_Test $test)
         if ($test instanceof \PHPUnit_Framework_TestCase) {
             $groups = array_merge($groups, \PHPUnit_Util_Test::getGroups(get_class($test), $test->getName(false)));
         }
+        if ($test instanceof \PHPUnit_Framework_TestSuite_DataProvider) {
```
Comment (eXorus) [inline src/Codeception/Lib/GroupManager.php]: ?? I don't understand

Comment (DavertMik) [inline src/Codeception/Lib/GroupManager.php]: don't worry )

**Comment by DavertMik** [comment]
Thank you. Sorry for delay, I was working on another PR and didn't have chance to review. Looks good to me.
