### PR TITLE
hotfix issue #5326

### LINKED ISSUE #5326: Doctrine `cleanup: true` not working
#### What are you trying to achieve?

Rollback the transcation.

#### What do you get instead?

Changes are kept in the database.

> Provide console output if related. Use `-vvv` mode for more details.

The output does start with:
> Scenario --
  [Database] Transaction started
  [Database] Transaction started

But this is *not* shown at the end of the output (no matter if the test passes or not):
> [Database] Transaction cancelled; all changes reverted.

### Details

* Codeception version: 2.5.2
* Symfony version: 4.2.1
* PHP Version: 7.2.10
* Suite configuration:

```yml
actor: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: 'src'
            environment: 'test'
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - REST:
            depends: Symfony
        - Asserts
        - \App\Tests\Helper\Functional
```

### PR DESCRIPTION
**Pull request by joelmedeiros**
Checking if there's transactions open and closing after the end of process when cleanup property is set. 

Fixes #5326

### CODE REVIEW

File: src/Codeception/Module/Doctrine2.php [hunk 1]
```diff
@@ -113,8 +113,56 @@ public function _before(TestInterface $test)
...
+
+            $this->em->getConnection()->beginTransaction();
+            $this->debugSection('Database', 'Transaction started');
+        }
+    }
+
+    /**
+     * @throws ModuleConfigException
+     */
+    public function onReconfigure()
```
Comment (Naktibalda) [inline src/Codeception/Module/Doctrine2.php]: Doctrine2 module has another `onReconfigure` method below this one.
```
PHP Fatal error:  Cannot redeclare Codeception\Module\Doctrine2::onReconfigure() in /home/travis/build/Codeception/Codeception/src/Codeception/Module/Doctrine2.php on line 174
```
