### PR TITLE
Symfony 3.3.0 compatibility

### LINKED ISSUE #4277: Symfony/console 3.3.0 broke `--xml` and other parameters with optional default value
https://travis-ci.org/Codeception/Codeception/jobs/237467274#L2737

```
1) IncludedCest: Run included with xml output
 Test  tests/cli/IncludedCest.php:runIncludedWithXmlOutput
 Step  See file found "report.json","tests/_output"
 Fail  File "report.xml" not found at ""

Scenario Steps:
 4. $I->seeFileFound("report.xml") at tests/cli/IncludedCest.php:42
 3. $I->amInPath("_log") at tests/cli/IncludedCest.php:41
 2. $I->executeCommand("run --xml") at tests/cli/IncludedCest.php:40
 1. $I->amInPath("tests/data/included") at tests/cli/IncludedCest.php:16
```

https://github.com/symfony/console/blob/master/CHANGELOG.md#330

> [BC BREAK] Input::getOption() no longer returns the default value for options with value optional explicitly passed empty

### PR DESCRIPTION
**Pull request by DavertMik**
Changed handling optional values in console options

Fixes #4277

### CODE REVIEW

File: src/Codeception/Codecept.php [hunk 1]
```diff
@@ -7,7 +7,7 @@
 
 class Codecept
 {
-    const VERSION = "2.3.2";
```
Comment (Naktibalda) [inline src/Codeception/Codecept.php]: I think that this change was made accidentally. Please revert it.

Comment (DavertMik) [inline src/Codeception/Codecept.php]: Yes... THX
