### PR TITLE
Bugfix issue #5163

### LINKED ISSUE #5163: [Yii2] Error: Call to a member function getDb() on null when running --html option
#### What are you trying to achieve?
Run tests using Yii2 module with HTML report generation.

#### What do you get instead?
Error during execution, even though tests pass, which seems to be only happening when running with --html option. If running without it execution doesn't break.

I'm not very familiar with Codeception source code but it seems like offending lines are in /codeception/codeception/src/Codeception/Step.php, where it tries to check __mocked property triggering db schema check. 
```
protected function getClassName($argument)
    {
        if ($argument instanceof \Closure) {
            return 'Closure';
        } elseif ((isset($argument->__mocked))) { // this line causes error
            return $this->formatClassName($argument->__mocked);
        }

        return $this->formatClassName(get_class($argument));
    }
```
It looks like the generation of HTML is triggered after Events::TEST_END is fired whereas application reset is happening before in Events::TEST_AFTER event:
```
public function endTest(\PHPUnit_Framework_Test $test, $time)
    {
        $hash = spl_object_hash($test);
        if (!in_array($hash, $this->unsuccessfulTests)) {
            $this->fire(Events::TEST_SUCCESS, new TestEvent($test, $time));
        }
        if (in_array($hash, $this->startedTests)) {
            $this->fire(Events::TEST_AFTER, new TestEvent($test, $time));
        }

        $this->dispatcher->dispatch(Events::TEST_END, new TestEvent($test, $time));
    }
```

> Provide console output if related. Use `-vvv` mode for more details.

```bash
[root@add1762f059c web]# ./vendor/bin/codecept clean && ./vendor/bin/codecept run tests/apiFunctional/customer/CustomerCest.php:itCreatesCustomer --html --debug
Cleaning up output /web/tests/_output/...
Done
Codeception PHP Testing Framework v2.4.5
Powered by PHPUnit 7.3.4 by Sebastian Bergmann and contributors.

Tests.apiFunctional Tests (1) -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: \tests\Helper\ApiFunctional, \tests\Helper\Fixture, Yii2, REST, Asserts, DataFactory
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  Printing HTML report into report.html
CustomerCreateCest: It creates customer
Signature: app\tests\apiFunctional\customer\CustomerCest:itCreatesCustomer
Test: tests/apiFunctional/customer/CustomerCest.php:itCreatesCustomer
Scenario --
  Destroying application
  Starting application
  [ConnectionWatcher] watching new connections
  [Fixtures] Loading fixtures
  [Fixtures] Done
  [TransactionForcer] watching new connections
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=testdb;dbname=xxx'
  [ConnectionWatcher] Connection opened!
  [TransactionForcer] Connection opened!
  [TransactionForcer] Transaction started for: mysql:host=testdb;dbname=xxx
 I have "app\common\models\Transaction",{"id":xxx}
  [yii\web\Session::open] 'Session started'
 I have "app\common\models\TransactionVehicle",{"transaction_id":xxx,"vehicle_id":xxx}
 I have auth token "app\\common\\models\\Transaction"
   I am bearer authenticated "xxxxxxxxxxxx.xxxxxxxxxxxx..."
 I send post "/api/customer/xxx",{"customer":{"title":"Mr","first_name":"Test","last_name":"test","phone":"xxxxxxxxxxxx","email":"xxxxxxxxxxxx","address_line1":"xxxxxxxxxxxx ...}
  [Request] POST http://localhost:8016/api/customer/xxx {"customer":{"title":"Mr","first_name":"Test","last_name":"test","phone":"xxxxxxxxxxxx","email":"xxxxxxxxxxxx","address_line1":"Test Line 1","address_line2":"Test Line 2","city":"TestCity","postcode":"xxxxxxxxxxxx"}}
  [Request Headers] {"Authorization":"Bearer xxxxxxxxxxxx.xxxxxxxxxxxx.xxx"}
  [yii\web\Session::freeze] 'Session frozen'
  [yii\web\Session::unfreeze] 'Session unfrozen'
  [yii\web\Session::freeze] 'Session frozen'
  [yii\web\Session::unfreeze] 'Session unfrozen'
  [yii\web\Session::init] 'Session is already started'
  [yii\web\User::login] 'User \'xxxxxx\' logged in from . Session not enabled.'
  [yii\filters\RateLimiter::beforeAction] 'Rate limit skipped: "user" does not implement RateLimitInterface.'
  [Page] http://localhost:8016/api/customer/transactionId
  [Response] 200
  [Request Cookies] []
  [Response Headers] xxxx
  [Response] {"_expand":"","data":{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"TestCity","postcode":"xxxxxxxxxxxx","hash":"xxx"}}
 I see response code is 200
 I grab response 
 I assert array has key "data",{"_expand":"","data":{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"xxxx...}
 I assert array has key "title",{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"TestCity","postcode":"xxx...}
 I assert array has key "firstName",{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"TestCity","postcode":...}
 I assert array has key "lastName",{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"TestCity","postcode":"...}
 I assert array has key "phone",{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"TestCity","postcode":"xxx...}
 I assert array has key "email",{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"TestCity","postcode":"xxx...}
 I assert array has key "line1",{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"TestCity","postcode":"xxx...}
 I assert array has key "line2",{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"TestCity","postcode":"xxx...}
 I assert array has key "city",{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"TestCity","postcode":"xxx...}
 I assert array has key "postcode",{"title":"Mr","firstName":"Test","lastName":"test","email":"xxxxxxxxxxxx","phone":"xxxxxxxxxxxx","line1":"Test Line 1","line2":"Test Line 2","city":"TestCity","postcode":"...}
 I see record "app\common\models\Customer",{"transaction_id":xxx}
  [app\common\models\TransactionCustomer] {}
 PASSED 

  [TransactionForcer] Transaction cancelled; all changes reverted.
  [TransactionForcer] no longer watching new connections
  [ConnectionWatcher] no longer watching new connections
  [ConnectionWatcher] closing all (1) connections
  Destroying application
An Error occurred while handling another error:
Error: Call to a member function has() on null in /web/vendor/yiisoft/yii2/web/ErrorHandler.php:91
Stack trace:
#0 /web/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(Error))
#1 [internal function]: yii\base\ErrorHandler->handleException(Object(Error))
#2 {main}
Previous exception:
Error: Call to a member function getDb() on null in /web/vendor/yiisoft/yii2/db/ActiveRecord.php:135
Stack trace:
#0 /web/vendor/yiisoft/yii2/db/ActiveRecord.php(377): yii\db\ActiveRecord::getDb()
#1 /web/vendor/yiisoft/yii2/db/ActiveRecord.php(413): yii\db\ActiveRecord::getTableSchema()
#2 /web/vendor/yiisoft/yii2/db/BaseActiveRecord.php(492): yii\db\ActiveRecord->attributes()
#3 /web/vendor/yiisoft/yii2/db/BaseActiveRecord.php(289): yii\db\BaseActiveRecord->hasAttribute('__mocked')
#4 /web/vendor/yiisoft/yii2/db/BaseActiveRecord.php(335): yii\db\BaseActiveRecord->__get('__mocked')
#5 /web/vendor/codeception/codeception/src/Codeception/Step.php(176): yii\db\BaseActiveRecord->__isset('__mocked')
#6 /web/vendor/codeception/codeception/src/Codeception/Step.php(164): Codeception\Step->getClassName(Object(app\common\models\Transaction))
#7 /web/vendor/codeception/codeception/src/Codeception/Step.php(103): Codeception\Step->stringifyArgument(Object(app\common\models\Transaction))
#8 /web/vendor/codeception/codeception/src/Codeception/Step/Meta.php(33): Codeception\Step->getArgumentsAsString(200)
#9 /web/vendor/codeception/codeception/src/Codeception/Step.php(235): Codeception\Step\Meta->getArgumentsAsString(200)
#10 /web/vendor/codeception/codeception/src/Codeception/Step.php(225): Codeception\Step->getHumanizedArguments()
#11 /web/vendor/codeception/phpunit-wrapper/src/ResultPrinter/HTML.php(293): Codeception\Step->getHtml()
#12 /web/vendor/codeception/phpunit-wrapper/src/ResultPrinter/HTML.php(114): Codeception\PHPUnit\ResultPrinter\HTML->renderSubsteps(Object(Codeception\Step\Meta), '      <tr>\n    ...')
#13 /web/vendor/phpunit/phpunit/src/Framework/TestResult.php(407): Codeception\PHPUnit\ResultPrinter\HTML->endTest(Object(Codeception\Test\Cest), 0.097566843032837)
#14 /web/vendor/codeception/codeception/src/Codeception/Test/Test.php(111): PHPUnit\Framework\TestResult->endTest(Object(Codeception\Test\Cest), 0.097566843032837)
#15 /web/vendor/phpunit/phpunit/src/Framework/TestSuite.php(750): Codeception\Test\Test->run(Object(PHPUnit\Framework\TestResult))
#16 /web/vendor/codeception/phpunit-wrapper/src/Runner.php(114): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#17 /web/vendor/codeception/codeception/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner->doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#18 /web/vendor/codeception/codeception/src/Codeception/Codecept.php(189): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#19 /web/vendor/codeception/codeception/src/Codeception/Codecept.php(158): Codeception\Codecept->runSuite(Array, 'apiFunctional', 'customer/Custom...')
#20 /web/vendor/codeception/codeception/src/Codeception/Command/Run.php(357): Codeception\Codecept->run('apiFunctional', 'customer/Custom...', Array)
#21 /web/vendor/symfony/console/Command/Command.php(251): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /web/vendor/symfony/console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /web/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /web/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /web/vendor/codeception/codeception/src/Codeception/Application.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /web/vendor/codeception/codeception/codecept(42): Codeception\Application->run()
#27 {main}
An Error occurred while handling another error:
Error: Call to a member function has() on null in /web/vendor/yiisoft/yii2/web/ErrorHandler.php:91
Stack trace:
#0 /web/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(Error))
#1 [internal function]: yii\base\ErrorHandler->handleException(Object(Error))
#2 {main}
Previous exception:
Error: Call to a member function getDb() on null in /web/vendor/yiisoft/yii2/db/ActiveRecord.php:135
Stack trace:
#0 /web/vendor/yiisoft/yii2/db/ActiveRecord.php(377): yii\db\ActiveRecord::getDb()
#1 /web/vendor/yiisoft/yii2/db/ActiveRecord.php(413): yii\db\ActiveRecord::getTableSchema()
#2 /web/vendor/yiisoft/yii2/db/BaseActiveRecord.php(492): yii\db\ActiveRecord->attributes()
#3 /web/vendor/yiisoft/yii2/db/BaseActiveRecord.php(289): yii\db\BaseActiveRecord->hasAttribute('__mocked')
#4 /web/vendor/yiisoft/yii2/db/BaseActiveRecord.php(335): yii\db\BaseActiveRecord->__get('__mocked')
#5 /web/vendor/codeception/codeception/src/Codeception/Step.php(176): yii\db\BaseActiveRecord->__isset('__mocked')
#6 /web/vendor/codeception/codeception/src/Codeception/Step.php(164): Codeception\Step->getClassName(Object(app\common\models\Transaction))
#7 /web/vendor/codeception/codeception/src/Codeception/Step.php(103): Codeception\Step->stringifyArgument(Object(app\common\models\Transaction))
#8 /web/vendor/codeception/codeception/src/Codeception/Step/Meta.php(33): Codeception\Step->getArgumentsAsString(200)
#9 /web/vendor/codeception/codeception/src/Codeception/Step.php(235): Codeception\Step\Meta->getArgumentsAsString(200)
#10 /web/vendor/codeception/codeception/src/Codeception/Step.php(225): Codeception\Step->getHumanizedArguments()
#11 /web/vendor/codeception/phpunit-wrapper/src/ResultPrinter/HTML.php(293): Codeception\Step->getHtml()
#12 /web/vendor/codeception/phpunit-wrapper/src/ResultPrinter/HTML.php(114): Codeception\PHPUnit\ResultPrinter\HTML->renderSubsteps(Object(Codeception\Step\Meta), '      <tr>\n    ...')
#13 /web/vendor/phpunit/phpunit/src/Framework/TestResult.php(407): Codeception\PHPUnit\ResultPrinter\HTML->endTest(Object(Codeception\Test\Cest), 0.097566843032837)
#14 /web/vendor/codeception/codeception/src/Codeception/Test/Test.php(111): PHPUnit\Framework\TestResult->endTest(Object(Codeception\Test\Cest), 0.097566843032837)
#15 /web/vendor/phpunit/phpunit/src/Framework/TestSuite.php(750): Codeception\Test\Test->run(Object(PHPUnit\Framework\TestResult))
#16 /web/vendor/codeception/phpunit-wrapper/src/Runner.php(114): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#17 /web/vendor/codeception/codeception/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner->doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#18 /web/vendor/codeception/codeception/src/Codeception/Codecept.php(189): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#19 /web/vendor/codeception/codeception/src/Codeception/Codecept.php(158): Codeception\Codecept->runSuite(Array, 'apiFunctional', 'customer/Custom...')
#20 /web/vendor/codeception/codeception/src/Codeception/Command/Run.php(357): Codeception\Codecept->run('apiFunctional', 'customer/Custom...', Array)
#21 /web/vendor/symfony/console/Command/Command.php(251): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /web/vendor/symfony/console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /web/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /web/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /web/vendor/codeception/codeception/src/Codeception/Application.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /web/vendor/codeception/codeception/codecept(42): Codeception\Application->run()
#27 {main}
```
> Provide test source code if related

```php
public function itCreatesCustomer(ApiFunctionalTester $I)
    {
        $transaction = $I->have(Transaction::class, []);
        $I->have(TransactionVehicle::class, [
            'transaction_id' => $transaction->id,
            'vehicle_id' => ApiFunctionalTester::VEHICLE_ID
        ]);
        $params = [
            'customer' => $this->getCustomerData()
        ];

        
        $I->haveAuthToken($transaction);
        $I->sendPOST(self::API_URL . $transaction->uuid, $params);
        $I->seeResponseCodeIs(200);
        $response = json_decode($I->grabResponse(), true);
        $I->assertArrayHasKey('data', $response);
        $data = $response['data'];
        $I->assertArrayHasKey('title', $data);
        $I->assertArrayHasKey('firstName', $data);
        $I->assertArrayHasKey('lastName', $data);
        $I->assertArrayHasKey('phone', $data);
        $I->assertArrayHasKey('email', $data);
        $I->assertArrayHasKey('line1', $data);
        $I->assertArrayHasKey('line2', $data);
        $I->assertArrayHasKey('city', $data);
        $I->assertArrayHasKey('postcode', $data);
        $I->seeRecord(Customer::class, ['transaction_id' => $transaction->id]);
    }
```
### Details

* Codeception version: 2.4.x-dev
* PHP Version: 7.2.8
* Operating System: Linux 4.9.76-3.78.amzn1.x86_64 GNU/Linux
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
```
{
  "name": "yiisoft/yii2-app-advanced",
  "description": "Yii 2 Advanced Application Template",
  "keywords": [
    "yii2",
    "framework",
    "advanced",
    "application template"
  ],
  "homepage": "http://www.yiiframework.com/",
  "type": "project",
  "license": "BSD-3-Clause",
  "support": {
    "issues": "https://github.com/yiisoft/yii2/issues?state=open",
    "forum": "http://www.yiiframework.com/forum/",
    "wiki": "http://www.yiiframework.com/wiki/",
    "irc": "irc://irc.freenode.net/yii",
    "source": "https://github.com/yiisoft/yii2"
  },
  "minimum-stability": "stable",
  "require": {
    "php": ">=7.2",
    "yiisoft/yii2": "2.0.15",
    "yiisoft/yii2-bootstrap": "*",
    "yiisoft/yii2-swiftmailer": "*",
    "yiisoft/yii2-httpclient": "*",
    "yiisoft/yii2-jui": "~2.0.0",
    "stripe/stripe-php": "4.*",
    "asofter/yii2-imperavi-redactor": "^0.0.3",
    "swagger-api/swagger-ui": "^3.10",
    "lcobucci/jwt": "^3.2",
    "aws/aws-sdk-php": "3.63.4",
    "bower-asset/jquery": "~2.2.4"
  },
  "require-dev": {
    "yiisoft/yii2-debug": "*",
    "yiisoft/yii2-gii": "*",
    "yiisoft/yii2-faker": "*",
    "codeception/codeception": "2.4.*-dev",
    "codeception/c3": "*",
    "codeception/visualception": "*",
    "codeception/phpbuiltinserver": "*",
    "codeception/robo-paracept": "dev-master",
    "micheh/teamcity-clover": "~0.6",
    "squizlabs/php_codesniffer": "3.*",
    "league/factory-muffin": "^3.0",
    "league/factory-muffin-faker": "^2.0"
  },
  "config": {
    "process-timeout": 1800
  },
  "autoload": {
    "psr-4": {
      "app\\": "./"
    }
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://asset-packagist.org"
    }
  ]
}
```
* Suite configuration:

```yml
namespace: tests
class_name: ApiFunctionalTester
modules:
    enabled:
        - tests\Helper\ApiFunctional
        - tests\Helper\Fixture
        - Yii2:
            transaction: true
            cleanup: true
            part: [orm, init, fixtures]
        - REST
        - Asserts
        - DataFactory
    config:
      REST:
        depends: Yii2
        url: http://localhost:8016
```

### PR DESCRIPTION
**Pull request by dh9325**
@DavertMik Are you able to have a look at this and review? I understand @SamMousa suggested removing `__mocked` property but not sure if that's would be an "easy fix", so just checking if class is implementing `PHPUnit\Framework\MockObject\MockObject` interface.

Closes #5163

### CODE REVIEW

File: src/Codeception/Step.php [hunk 1]
```diff
@@ -173,7 +174,7 @@ protected function getClassName($argument)
     {
         if ($argument instanceof \Closure) {
             return 'Closure';
-        } elseif ((isset($argument->__mocked))) {
+        } elseif (in_array(MockObject::class, class_implements(get_class($argument)))) {
```
Comment (SamMousa) [inline src/Codeception/Step.php]: Why not use `instanceof`?

Comment (SamMousa) [inline src/Codeception/Step.php]:
```suggestion
        } elseif ($argument instanceof MockObject) {
```

File: src/Codeception/Step.php [hunk 2]
```diff
@@ -173,7 +174,7 @@ protected function getClassName($argument)
     {
         if ($argument instanceof \Closure) {
             return 'Closure';
-        } elseif ((isset($argument->__mocked))) {
+span class="pl-s1">         } elseif ($argument instanceof MockObject) {
```
[the remark this answers is not in the document]
Comment (SamMousa) [reply src/Codeception/Step.php]: It seems something went wrong with github suggestion feature, this is cleary wrong.

**Comment by SamMousa** [comment]
LGTM, will merge when tests finish.

File: src/Codeception/Step.php [hunk 3]
```diff
@@ -173,7 +174,7 @@ protected function getClassName($argument)
     {
         if ($argument instanceof \Closure) {
             return 'Closure';
-        } elseif ((isset($argument->__mocked))) {
+        } elseif ($argument instanceof MockObject) {
             return $this->formatClassName($argument->__mocked);
```
Comment (DavertMik) [inline src/Codeception/Step.php]: Ok, what if there is no `__mocked` property but an object is still MockObject?

**Comment by DavertMik** [comment]
Please don't mark the PR with [Yii] if it's not Yii related.

**Comment by DavertMik** [comment]
I think the better way is to remove `__mocked`...
Sorry I have no time to investigate if it's spossible to do without concequinces

File: src/Codeception/Step.php (hunk 3 above)
Comment (dh9325) [reply src/Codeception/Step.php]: @DavertMik Have applied changes as requested but AppVeyor build failed

`elseif ($argument instanceof MockObject && isset($argument->__mocked)` are you happy with this?

**Comment by dh9325** [comment]
@SamMousa @samdark Any chance to have a look at failing AppVeyor build? It doesn't seem to be related to the code changes. Thanks
