### PR TITLE
JsonType: Allow to use : in regex filter

### LINKED ISSUE #2501: \Codeception\Util\JsonType filter delimiter ":" does not allow to use ":" in regex filter
`````` $I->seeResponseMatchesJsonType([
"created_at" => "string:regex(~\d{2}\/\d{2}\/\d{4} \d{2}:\d{2}:\d{2}~)"
]);```

will cause an error for {"created_at":"29/10/2015 08:15:44"}
because of explode by ":" that will break regex pattern,
but it's wrong.

I can use custom filter like a workaround, but the documentation confuses
me hiding the fact that ":" can not be used in regex.
``````

### PR DESCRIPTION
**Pull request by ellisgl**
Fixes #2501 
Fixes regex filter handling in Util\JsonType

### CODE REVIEW

File: src/Codeception/Util/JsonType.php [hunk 1]
```diff
@@ -126,14 +126,25 @@ protected function typeComparison($data, $jsonType)
...
                 continue;
             }
-            $matchTypes = preg_split("#(?![^]\(]*\))\|#", $type);
-            $matched = false;
+
+            $regexes = [];
+
+            preg_match_all('/:regex\((.*?[!"#$%&\'*+,.\/:;=?@^_`|~-])\)/', $type, $regexes);
+
+            $type = preg_replace_callback('/:regex\((.*?[!"#$%&\'*+,.\/:;=?@^_`|~-])\)/', function ($m) {
```
Comment (DavertMik) [inline src/Codeception/Util/JsonType.php]: could you explain a bit of this magic?

**Comment by DavertMik** [comment]
Looks good to me but I don't understand what's happening there :stuck_out_tongue: 
Could you add some inline comments to your code?
I know regex is complicated by itself but some minor comments would help

File: src/Codeception/Util/JsonType.php (hunk 1 above)
Comment (ellisgl) [reply src/Codeception/Util/JsonType.php]: So what's happening here's it's matching for everything up to the regex closing delimiter (This should cover 99.999% of the delimiter usage - There are some strange ones like '<'...'>' and '{'...'}' which I've only come across a couple times in my lifetime.). What was happening before was that stuff like ':' was causing the match to match prematurely, so adding the closing delimiter match after wildcard and before the ')' character, it shouldn't get tripped up.

**Comment by ellisgl** [comment]
Looks like wercker/build stuff needs to fixed.

File: src/Codeception/Util/JsonType.php (hunk 1 above)
Comment (Naktibalda) [reply src/Codeception/Util/JsonType.php]: Just use the first character as a delimiter, that's what preg_match does.

Comment (ellisgl) [reply src/Codeception/Util/JsonType.php]: Well the offending code was preg_split, which was looking for ':', which would break if ':' was in the regex filter definition. So this is what I first thought of. There is the (?R) recursive pattern, but I would have to look over that again, since it's probably been over 10 years since I've used that.

Comment (ellisgl) [reply src/Codeception/Util/JsonType.php]: @DavertMik @Naktibalda I've updated my explanation on the how and why.

File: tests/unit/Codeception/Util/JsonTypeTest.php [hunk 2]
```diff
@@ -82,6 +82,12 @@ public function testRegexFilter()
 
         $jsonType = new \Codeception\Util\JsonType(['time' => '21:00']);
         $this->assertTrue($jsonType->matches(['time' => 'string:regex(~^([0-1]\d|2[0-3]):[0-5]\d$~)']));
+        
+        $jsonType = new \Codeception\Util\JsonType(['text' => '21@:00']);
+        $this->assertTrue($jsonType->matches(['text' => 'string:regex(~^(\d\d@):\dd$~)']));
+        
+        $jsonType = new \Codeception\Util\JsonType(['text' => '21@:aa']);
+        $this->assertFalse($jsonType->matches(['text' => 'string:regex(~^(\d\d@):\dd$~)']));
```
[the remark this answers is not in the document]
Comment (Naktibalda) [reply tests/unit/Codeception/Util/JsonTypeTest.php]: Sorry for that, let's see if fixing it helps.

**Comment by Naktibalda** [comment]
I tried to match time with `'time' => 'string:regex(~\d\d:\d\d:\d\d~)',` in my project,
so I copy-pasted your patch to see if it works.
Matching works correctly, but one thing it messes up is error message.

Here is the output I got:
```
 Fail  `time: '2018-12-21'` is of type `string:regex($$0)`
```
I would like to see the actual pattern instead of `$$0`.

This issue was visible in my failed attempt to create failing test: https://travis-ci.org/Codeception/Codeception/jobs/467890679
```
Failed asserting that '`text: '21@:00'` is of type `string:regex($$0):\dd$~)`' is true.
```

**Comment by Naktibalda** [comment]
It should be enough to use a different variable instead of `$type` to store result of `preg_replace_callback` to avoid overriding original value of `$type`.

**Comment by ellisgl** [comment]
OK - so there actually was an issue with the regex I was using which prematurely stopped on that example you gave (Which I had a pattern I wrote during the last commit that I thought was overkill, but I guess it wasn't). I also had to just replace the $$\d+ in the type. Reason for this was because of the split on | and the split on : would have still caused some issues if I had just used a second variable for the regexes. I also did some fixes around PHP Inspections (EA Extended) suggestions.

File: src/Codeception/Util/JsonType.php [hunk 3]
```diff
@@ -119,55 +119,71 @@ protected function typeComparison($data, $jsonType)
...
             $regexes = [];
 
             // Match the string ':regex(' and any characters until a regex delimiter (matches 99.999% use cases) followed by character ')'
             // Place the 'any character' + delimiter matches in to an array.
-            preg_match_all('/:regex\((.*?[!"#$%&\'*+,.\/:;=?@^_`|~-])\)/', $type, $regexes);
+            preg_match_all($regexMatcher, $type, $regexes);
 
             // Do the same match as above, but replace the the 'any character' + delimiter with a place holder ($${count}).
-            $type = preg_replace_callback('/:regex\((.*?[!"#$%&\'*+,.\/:;=?@^_`|~-])\)/', function ($m) {
+            $type = preg_replace_callback($regexMatcher, function ($m) {
```
Comment (Naktibalda) [inline src/Codeception/Util/JsonType.php]: Using different variable name instead of `$type` here and in the `preg_split` below would avoid need to refill at the bottom.

Comment (ellisgl) [reply src/Codeception/Util/JsonType.php]: Ah!
