### PR TITLE
fix #3866 grabValueFrom doesn't work with fillField

### LINKED ISSUE #3866: grabValueFrom doesn't work with fillField
>test code is:
```php
$I->fillField('username', 'admin');
codecept_debug($I->grabValueFrom('[name=username]'));
$I->click('Login');
```
> run with ``--debug`` option, will get output like:
```bash
   I grab value from "[name=username]"
  
   I click "Login"
```
> no value ouputed here. notice that the empty line is my expected output location of value.

> I found the issue in last line of method `CodeCeption\Lib\InnerBrowser::fillField`:
```php
$input->getNode(0)->nodeValue = htmlspecialchars($value);
```
> the point is input field must be have no nodeValue, and `grabValueFrom` use the right way to get value. I think the right code should be like:
```php
$input->getNode(0)->setAttribute('value', htmlspecialchars($value));
``` 
> I tried to change to this, it works

> I think a test for `CodeCeption\Lib\InnerBrowser` will be good.

### PR DESCRIPTION
**Pull request by wumouse**
fix issue 3866

### CODE REVIEW

**Comment by wumouse** [comment]
#3866

File: tests/unit/Codeception/Module/TestsForWeb.php [hunk 1]
```diff
@@ -691,6 +691,17 @@ public function testGrabValueFrom()
         $this->module->amOnPage('/form/select');
         $result = $this->module->grabValueFrom('#age');
         $this->assertEquals('oldfag', $result);
+
+        $this->module->amOnPage('/form/bug3866');
```
Comment (DavertMik) [inline tests/unit/Codeception/Module/TestsForWeb.php]: big thanks for this PR, and especially for test, but could you move this to separate test so it would be easier to find it? Thanks

Comment (wumouse) [inline tests/unit/Codeception/Module/TestsForWeb.php]: 👌

**Comment by wumouse** [comment]
@DavertMik Please review the new commit, thank you

**Comment by wumouse** [comment]
@Naktibalda Oh, yes! it fixed `seeInField` too.
