### PR TITLE
[REST] Don't fail dontSee*JsonPath assertions when response is scalar…

### LINKED ISSUE #4237: JsonPath fails in 2.2.12
#### What are you trying to achieve?
JsonPath related method failing in codecept 2.2.12, working in 2.2.11.

#### What do you get instead?
See output below.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
 Step  Don't see response json matches json path "$.error"
 Fail  JSON response is not an array: true
```
> Provide test source code if related
Response: true

```php
$I->dontSeeResponseJsonMatchesJsonPath('$.error');
```
### Details

* Codeception version: 2.2.12, flow/jsonpath 0.3.4
* PHP Version: 7.1
* Operating System: linux
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

### PR DESCRIPTION
**Pull request by Naktibalda**
… value

Closes #4237

### CODE REVIEW

File: src/Codeception/PHPUnit/Constraint/JsonContains.php [hunk 1]
```diff
@@ -31,6 +31,9 @@ public function __construct(array $expected)
     protected function matches($other)
     {
         $jsonResponseArray = new JsonArray($other);
+        if (!is_array($jsonResponseArray->toArray())) {
+            throw new \PHPUnit_Framework_AssertionFailedError('JSON response is not an array: ' . $other);
```
Comment (DavertMik) [inline src/Codeception/PHPUnit/Constraint/JsonContains.php]:
```php
$this->fail('JSON response is not an array: ' . $other)
```

**Comment by DavertMik** [comment]
Ok, thanks!
