### PR TITLE
Fixing Module.php constuctor and getConfig phpdoc parameter definitions

### LINKED ISSUE #5466: Faulty `null` phpdoc parameter signatures in `Module.php`
#### What are you trying to achieve?
Run phpstan on my project with lvl7 without any warnings and errors.

#### What do you get instead?
Two types of issues discovered so far both located in `Module.php`
Both issues are related to a faulty phpdoc signature given for parameters.
- `Parameter #1 $key of method Codeception\Module::_getConfig() expects null, string given.`
- `Parameter #2 $config of method Codeception\Module::__construct() expects null, array given.` 

The parameters are optional with a default `null` value.
The parameter definition states only null.
This is not really the case tho, as in both occasions (array in first example, mixed in the second one) null is only the default value.

### Details
* Codeception version: 2.5.5
* PHP Version: 7.2.11
* Operating System: Docker
* Installation type: Docker pull

### PR DESCRIPTION
**Pull request by OneEyedSpaceFish**
Fixes #5466

### CODE REVIEW

File: src/Codeception/Module.php [hunk 1]
```diff
@@ -345,7 +345,7 @@ protected function getModule($name)
     /**
      * Get config values or specific config item.
      *
-     * @param null $key
+     * @param mixed|null $key
```
Comment (Naktibalda) [inline src/Codeception/Module.php]: Is there any point to keep |null after mixed?
I think that this line and return line can be simplified to mixed type.
`@return array|mixed|null` -> `@return mixed`

Comment (OneEyedSpaceFish) [reply src/Codeception/Module.php]: 1/ maybe not
2/ agreed

**Comment by OneEyedSpaceFish** [comment]
I am not sure why the Semaphore build failed, I assume it has nothing to do with the changes?
