### PR TITLE
[WebDriver] Fix #4846

### LINKED ISSUE #4846: see() with strict CSS locator has problem with phpunit 7 typehint
#### What are you trying to achieve?

Use `$webDriver->see('text', ['css' => '.class'])`

This fails because phpunit `Assert::assertThat($haystack, Constraint $constraint, string $message = '')` has third paramether typehinted as a string. Array `['css' => '.class']` is given.

#### What do you get instead?

```bash
There was 1 error:
...                                                                                                                                                                                                                                            
  [TypeError] Argument 3 passed to PHPUnit\Framework\Assert::assertThat() must be of the type string, array given, called in /var/www/shopsys-framework/vendor/codeception/codeception/src/Codeception/Util/Shared/Asserts.php on line 289  
                                                                                                                                                                                                                                            
...

/var/www/shopsys-framework/vendor/phpunit/phpunit/src/Framework/Assert.php:2205
/var/www/shopsys-framework/vendor/codeception/codeception/src/Codeception/Util/Shared/Asserts.php:289
/var/www/shopsys-framework/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:2856
/var/www/shopsys-framework/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:882
...

ERRORS!
Tests: 1, Assertions: 1, Errors: 1.

```

### Details

* Codeception version: 2.4.0
* PHP Version: 7.2.2
* Operating System: Ubuntu 16.04
* Installation type: Composer
* List of installed packages (`composer show`)

```bash
phpunit/php-code-coverage            6.0.1                                                           Library that provides collection, processing, and rendering functionality for PHP code coverage ...
phpunit/php-file-iterator            1.4.5                                                           FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template            1.2.1                                                           Simple template engine.
phpunit/php-timer                    2.0.0                                                           Utility class for timing
phpunit/php-token-stream             3.0.0                                                           Wrapper around PHP's tokenizer extension.
phpunit/phpunit                      7.0.2                                                           The PHP Unit Testing framework.
phpunit/phpunit-mock-objects         6.0.1
sebastian/code-unit-reverse-lookup   1.0.1                                                           Looks up which function or method a line of code belongs to
sebastian/comparator                 2.1.3                                                           Provides the functionality to compare PHP values for equality
sebastian/diff                       3.0.0                                                           Diff implementation
sebastian/environment                3.1.0                                                           Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   3.1.0                                                           Provides the functionality to export PHP variables for visualization
sebastian/global-state               2.0.0                                                           Snapshotting of global state
sebastian/object-enumerator          3.0.3                                                           Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector           1.1.1                                                           Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context          3.0.0                                                           Provides functionality to recursively process PHP variables
sebastian/resource-operations        1.0.0                                                           Provides a list of PHP built-in functions that operate on resources
sebastian/version                    2.0.1
codeception/codeception              2.4.0                                                           BDD-style testing framework
codeception/phpunit-wrapper          7.0.2                                                           PHPUnit classes used by Codeception
codeception/stub                     1.0.2
```
* Suite configuration:

### PR DESCRIPTION
**Pull request by edno**
Fix  **WebDriver** module issue when `see()` and `dontSee() ` are used with array selector.

Fixes #4846

### CODE REVIEW

File: src/Codeception/Module/WebDriver.php [hunk 1]
```diff
@@ -2867,12 +2867,21 @@ protected function convertKeyModifier($keys)
...
     {
-        $this->assertThat($nodes, new WebDriverConstraintNot($text, $this->_getCurrentUri()), $selector);
+        $this->assertNodeConstraint($nodes, new WebDriverConstraintNot($text, $this->_getCurrentUri()), $selector);
+    }
+
+    protected function assertNodeConstraint($nodes, WebDriverConstraint $constraint, $selector = null)
+    {
+        $message = $selector;
+        if (is_array($selector)) {
+            $message = implode(array_keys($selector)) . ':' . implode($selector);
```
Comment (Naktibalda) [inline src/Codeception/Module/WebDriver.php]: Result of implode without separator can be confusing if $selector array contains multiple items.
I think that it would be better to replicate behaviour of [getStrictLocator](https://github.com/Codeception/Codeception/blob/2.4.1/src/Codeception/Module/WebDriver.php#L2771-L2772) method
```php
$type = key($selector);
$locator = $selector[$type];
```

Comment (Naktibalda) [reply src/Codeception/Module/WebDriver.php]: @edno have you got any objections to proposed change?

**Comment by magroski** [comment]
any updates on this?

**Comment by weshooper** [comment]
Thanks for this @edno 😄Be great to get this released and move on to PHPUnit 7!

**Comment by Naktibalda** [comment]
3 months have passed, so I implemented my own suggestion.
@DavertMik Please review.

**Comment by edno** [comment]
Sorry for late reply. 
@Naktibalda, I agree your solution is more robust and consistent with other methods :-)

**Comment by spaceman-cb** [comment]
Any word on when this will be released officially?
