### PR TITLE
Fix g:scenarios --single-file missing linebreaks between scenarios

### LINKED ISSUE #1866: Incorrect scenarios generation for Cests
When I run: `php ~/codecept.phar g:scenarios acceptance --path tests/doc`

I get the following output (5 tests there):                                                                          
* Checkout generated
* Checkout generated
* Checkout generated
* Checkout generated
* Checkout generated

But in the resulting Checkout.txt only the first test scenario is listed. I'm I doing something wrong or this is an issue?

It looks like `--single-file` option works correctly generating all the scenarios, but the txt formatting is slightly broken, e.g. no linebreaks between tests. I would gladly contribute some fixes for this if the issue is confirmed

### PR DESCRIPTION
**Pull request by Zifius**
Partially resolves #1866

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks!

File: tests/cli/GenerateScenariosCept.php [hunk 1]
```diff
@@ -1,6 +1,6 @@
 <?php
 $I = new CliGuy($scenario);
-$I->wantTo('generate scenarios сценарий');
+$I->wantTo('generate test scenario');
```
Comment (sergeyklay) [inline tests/cli/GenerateScenariosCept.php]: :+1:
